one = float(input("Введиче первое вещественное число:  "))
print(int(one))
print(float(one))
print(bool(one))
print(str(one))
two = float(input("Введиче второе вещественное число:  "))
print("Два целых числа:")
print(int(one), "+", int(two), "=", int(one) + int(two))
print(int(one), "*", int(two), "=", int(one) * int(two))
print("Целое число и вещественное число:")
print(int(one), "+", two, "=", one + two)
print(int(one), "*", two, "=", int(one) * two)
print("Два вещественных числа:")
print(one, "+", two, "=", one + two)
print(one, "*", two, "=", one * two)
print("Две строки:")
print(str(one), "+", str(two), "=", str(one) + str(two))
print("Целое число и логические число:")
print(int(one), "+", bool(two), "=", int(one) + bool(two))
print(int(one), "*", bool(two), "=", int(one) * bool(two))
print("Вещественное число и логические число:")
print(float(one), "+", bool(two), "=", float(one) + bool(two))
print(float(one), "*", bool(two), "=", float(one) * bool(two))
print("Два логических числа")
print(bool(one), "+", bool(two), "=", bool(one) + bool(two))
print(bool(one), "*", bool(two), "=", bool(one) * bool(two))
print("Строка и логические число:")
print(str(one), "*", bool(two), "=", str(one) * bool(two))
