name = input("Введите своё имя и фамилию:  ")
print("Привет", name)
print("-------------")
now_day = int(input("Введите число сегодняшнего дня:  "))
now_month = int(input("Введите число сегодняшнего месяца:  "))
now_year = int(input("Введите число сегодняшнего года:  "))
print("-------------")
day = int(input("Введите день даты своего рождения:  "))
month = int(input("Введите месяц даты своего рождения:  "))
year = int(input("Введите год даты своего рождения:  "))
print("-------------")
month = (year*12 + month)
day = (month*30 + day)
now_month = (now_year*12 + now_month)
now_day = (now_month*30 + now_day)
now_old = int((now_day - day)/360)
print("Количесво прожитых Вами лет:  ", now_old)
print("Количесво прожитых Вами месяцев: ", now_month - month)
start_old = int((726829 - day)/360)
start_month = int((726829 - day)/30)
start_day = int(726829 - day)
print("-------------")
print("Количесво прожитых Вами лет до даты начала курса:  ", start_old)
print("Количесво прожитых Вами месяцев до даты начала курса:  ", start_month)
print("Количесво прожитых Вами дней до даты начала курса:  ", start_day)
